### ISSUE TITLE
Comparing your way of doing things with mine...

### ISSUE THREAD

**Issue by mauriciosoares** [fdecampredon/react-rxjs-todomvc#5]
Hello François (@fdecampredon), thanks for this project, I'm learning a lot of how to integrate react and rxjs with it.

If you have a few time, I'd like to ask you what you think about this approach of doing stores and actions:
https://github.com/mauriciosoares/rxjs-react-example/blob/master/app/actions/todo.js
https://github.com/mauriciosoares/rxjs-react-example/blob/master/app/stores/todos.js

I mean, I think the approach I'm using is cleaner, and achieves the same result as yours... and it seems to be easier to understand.

Also It seems that you're doing too much logic in the actions, should't them be placed at the store?

I'm not judging your code, please don't get me wrong. I'm only willing to understand the advantages of using your approach, since I'm only a mere beginner in terms of rxjs and React :)

Cheers!

**Comment by fdecampredon** [comment]
firstly this an old implementation, I'll definitely address thing differently today. and yes I would put less logic in action today, however I still do prefer 'scan'  a la redux than manually pushing todos to a subject. also your 'add' action use push and I try to avoid mutation.

**Comment by mauriciosoares** [comment]
cool, I'll check how I can improve my coding considering your thoughts, :)

Thanks @fdecampredon
